"""Turn a validated submission GeoTIFF into a compact payload the website can
re-generate in the browser.

Why: the brief says the site itself must be able to produce the .tif that gets
uploaded. A static page cannot run GDAL, but it can rebuild the exact pixels from
a compact run-length payload and *prove* the rebuild with a SHA-256 over the raw
little-endian float32 array, which is independent of the compressor. If the hash
matches, the browser-made file is semantically the same raster as the built,
format-gated artifact.

Payload format (little-endian, documented so it can be audited by hand)::

    magic       5 bytes  b"G7PL1"
    rows        uint32
    cols        uint32
    per row:    uint32 n_runs, then n_runs * (varint run_length, uint8 code)
                codes: 0 -> 0.0, 1 -> 1.0, 2 -> NaN   (runs must sum to cols)

Outputs
-------
* ``assets/submission_payload.js``  (payload + hashes + provenance for the page)
* ``downloads/<name>.payload.json`` (machine-readable manifest, no pixel data)
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import struct
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]


def encode_rle(codes: np.ndarray) -> bytes:
    rows, cols = codes.shape
    out = bytearray(b"G7PL1")
    out += struct.pack("<II", rows, cols)
    for r in range(rows):
        row = codes[r]
        # run-length boundaries
        change = np.flatnonzero(np.diff(row)) + 1
        starts = np.concatenate(([0], change))
        ends = np.concatenate((change, [cols]))
        out += struct.pack("<I", len(starts))
        for s, e in zip(starts, ends):
            n = int(e - s)
            while True:                      # LEB128 varint
                b = n & 0x7F
                n >>= 7
                out.append(b | (0x80 if n else 0x00))
                if not n:
                    break
            out.append(int(row[s]))
    return bytes(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tif", default="downloads/gems7-lidarscarp-ridge-top2pct-36c3a3f341c8.tif")
    ap.add_argument("--note", default="Lidar scarp model, ridge-thinned top 2% | 36c3a3f341c8")
    ap.add_argument("--out-js", default="assets/submission_payload.js")
    ap.add_argument("--out-json", default=None)
    args = ap.parse_args(argv)

    import rasterio

    tif = ROOT / args.tif
    with rasterio.open(tif) as s:
        arr = s.read(1)
        grid = {"width": s.width, "height": s.height, "crs": str(s.crs),
                "transform": list(tuple(s.transform)[:6]), "dtype": s.dtypes[0]}
    codes = np.zeros(arr.shape, dtype=np.uint8)
    finite = np.isfinite(arr)
    codes[finite & (arr == 0)] = 0
    codes[finite & (arr != 0)] = 1
    codes[~finite] = 2
    payload = encode_rle(codes)
    pixels = np.where(np.isfinite(arr), arr, np.float32(np.nan)).astype("<f4").tobytes()
    man = {
        "purpose": ("compact payload the public site rebuilds into the exact float32 submission raster; "
                    "pixels are verified by SHA-256 over the raw little-endian float32 array"),
        "format": "see scripts/build_browser_payload.py docstring (G7PL1 run-length)",
        "source_artifact": args.tif,
        "source_artifact_sha256": hashlib.sha256(tif.read_bytes()).hexdigest(),
        "pixel_payload_sha256": hashlib.sha256(pixels).hexdigest(),
        "pixel_payload_bytes": len(pixels),
        "payload_bytes": len(payload),
        "payload_base64_bytes": len(base64.b64encode(payload)),
        "grid": grid,
        "value_codes": {"0": 0.0, "1": 1.0, "2": "NaN"},
        "counts": {"zero": int((codes == 0).sum()), "one": int((codes == 1).sum()),
                   "nan": int((codes == 2).sum())},
        "suggested_submission_note": args.note,
    }
    js = ("// Generated by scripts/build_browser_payload.py -- do not edit.\n"
          "window.GEMS_SUBMISSION_PAYLOAD = " + json.dumps({
              "manifest": man,
              "base64": base64.b64encode(payload).decode("ascii"),
          }) + ";\n")
    out_js = ROOT / args.out_js
    out_js.parent.mkdir(parents=True, exist_ok=True)
    out_js.write_text(js)
    out_json = Path(args.out_json) if args.out_json else (ROOT / "downloads" / (tif.stem + ".payload.json"))
    out_json.write_text(json.dumps(man, indent=1))
    print(json.dumps({k: man[k] for k in ("pixel_payload_sha256", "payload_bytes", "payload_base64_bytes",
                                          "counts", "source_artifact_sha256")}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
